### ISSUE TITLE
Could parse .gitreview

### ISSUE THREAD

**Issue by agx** [berrange/gerrymander#10]
Hi,
it would be awesome if gerrymander would parse .gitreview files for the [server] section. This would make it simpler to use it for different projects besides openstack

**Comment by larsks** [comment]
I came here to file exactly the same request.  Hey, @berrange , is this still something you're developing (i.e., if I submit a PR, will you look at it)?

**Comment by berrange** [comment]
If you want to submit a patch to parse .gitreview, that's fine with me

**Comment by berrange** [comment]
Addressed in git master in

commit f19b229339d722f98b3c478918e10ba3cff225a6
Author: Lars Kellogg-Stedman <lars@redhat.com>
Date:   Tue Feb 16 10:30:36 2016 -0500

    add support for getting gerrit server from git remote
    
    With this change, you can configure your `.gerrymander` file like
    this:
    
        [server]
        remote = gerrit
    
    And gerrymander will read the user, host, and port from the named
    remote in whatever git repository you happen to be using at the time.
    This is especially convenient when your work environment includes
    projects hosted at multiple gerrit sites.
