### ISSUE TITLE
todo-others returns your own patches

### ISSUE THREAD

**Issue by mdbooth** [berrange/gerrymander#25]
I assume it's just looking at reviews, so returning any of your own patches which you haven't also reviewed. This is a bit counterintuitive.

**Comment by berrange** [comment]
commit a754cebf26d543822333958dfecc2441429654e5
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Wed Feb 17 11:16:34 2016 +0000

    Don't include your own changes in todo lists
    
    The todo lists are for identifying various changes that you
    may be interested in reviewing. People don't review their
    own changes, so these should all be filtered out.
    
    Fixes bug #25
